version: "3.4"

services:

  api:
    build:
      context: ./api
    volumes:
      - ./api/src/:/app/src
    environment:
      APP_LOG: /logs/tutorial.log
      FLASK_APP: src.app_factory:create_app()
      FLASK_RUN_HOST: 0.0.0.0
      PYTHONPATH: /app:${PYTHONPATH}
      SQLITE_TEMP_DIR: /sqlite_temp
      JWT_ACCESS_LIFESPAN: '30s'
      JWT_REFRESH_LIFESPAN: '2m'
      MAIL_SERVER: mailer
      PRAETORIAN_CONFIRMATION_SENDER: "demo@tutorial.com"
      PRAETORIAN_CONFIRMATION_URI: "http://localhost:4200/register-confirm"
      SETUPTOOLS_USE_DISTUTILS: "stdlib"
    ports: ['5000:5000']

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile-dev
    volumes:
      - ./ui/src:/app/src
      - ./ui/angular.json:/app/angular.json
      - ./ui/browserslist:/app/browserslist
      - ./ui/jest.config.js:/app/jest.config.js
      - ./ui/tsconfig.json:/app/tsconfig.json
      - ./ui/tsconfig.app.json:/app/tsconfig.app.json
      - ./ui/tslint.json:/app/tslint.json
    ports: ['4200:4200']

  mailer:
    image: djfarrelly/maildev
    ports:
      - 1080:80
